# .github/workflows/pytest.yaml
name: Python Unit Tests

on:
  pull_request:
    branches:
      - main
  workflow_run:
    workflows: ["Docker Compose Build and Test"]  # Name of your docker-compose workflow
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/question_service  # Set working directory for all run steps

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up environment variables for backend
      run: |
        echo "CRED_PATH=./firebase-cred.json" > .env

    - name: Add Firebase credentials
      run: |
        echo "${{ secrets.FIREBASE_CRED_JSON }}" > firebase-cred.json

    - name: Run tests with pytest
      run: |
        pytest tests/ -v --cov=app --cov-report=xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./backend/question_service/coverage.xml
        flags: pytests
        name: codecov-umbrella
        fail_ci_if_error: true

    - name: Upload test results
      if: always()  # Upload test results even if tests fail
      uses: actions/upload-artifact@v3
      with:
        name: pytest-results
        path: |
          ./backend/question_service/coverage.xml
          ./backend/question_service/.coverage