# .github/workflows/pytest.yaml
name: Python Unit Tests

on:
  pull_request:
    branches:
      - main
  workflow_run:
    workflows: ["Docker Compose Build and Test"]  # Name of your docker-compose workflow
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Only run if docker-compose workflow succeeded
    defaults:
      run:
        working-directory: ./backend/question_service  # Set working directory for all run steps

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create mock Firebase credentials
      run: |
        echo '{
          "type": "service_account",
          "project_id": "mock-project",
          "private_key_id": "mock-key-id",
          "private_key": "mock-private-key",
          "client_email": "mock@mock-project.iam.gserviceaccount.com",
          "client_id": "mock-client-id",
          "auth_uri": "https://accounts.google.com/o/oauth2/auth",
          "token_uri": "https://oauth2.googleapis.com/token",
          "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
          "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/mock@mock-project.iam.gserviceaccount.com"
        }' > firebase-credentials.json
      working-directory: ./backend/question_service

    - name: Set environment variables
      run: |
        echo "CRED_PATH=$GITHUB_WORKSPACE/backend/question_service/firebase-credentials.json" >> $GITHUB_ENV

    - name: Run tests with pytest
      run: |
        pytest tests/ -v --cov=app --cov-report=xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./backend/question_service/coverage.xml
        flags: pytests
        name: codecov-umbrella
        fail_ci_if_error: true

    - name: Upload test results
      if: always()  # Upload test results even if tests fail
      uses: actions/upload-artifact@v3
      with:
        name: pytest-results
        path: |
          ./backend/question_service/coverage.xml
          ./backend/question_service/.coverage